### ISSUE TITLE
Binary Tree: Selected Problems for practice

### ISSUE THREAD

**Issue by RAGHAVS1304** [VGandhi27/hacktoberfest-2023#19]
# Selected Problems of Binary Tree

- Preorder, Inorder, Postorder Traversals in One Traversal
- Maximum depth of a Binary Tree
- Calculate the Diameter of a Binary Tree
- Check if the Binary Tree is Balanced Binary Tree
- Maximum Width of a Binary Tree
- Check if two trees are identical
Practicing these problems give solid foundation in binary tree data structure.

**Comment by RAGHAVS1304** [comment]
I will be adding some best problems of binary tree please assign this issue to me.
Thanks

**Comment by RAGHAVS1304** [comment]
I have raised the PR, please Review it
Thanks

**Comment by VGandhi27** [comment]
okay
