### ISSUE TITLE
Add java GUI projects

### ISSUE THREAD

**Issue by joefreddiecheeran** [VGandhi27/hacktoberfest-2023#30]
I would like to add a car rental service GUI made using Swing in java. Can you assign this to me with hacktoberfest-accepted label?

**Comment by VGandhi27** [comment]
Ya sure @joefreddiecheeran

**Comment by joefreddiecheeran** [comment]
> Ya sure @joefreddiecheeran 

I think you closed this, can you assign it to me please?
